version: '3'
services:
    node:
        build: ./docker/node
        volumes:
            - ./frontend:/home/www/code
        working_dir: /home/www/code
        tty: true
        ports:
            - "3000:3000"
    web:
        image: nginx:1.15.7-alpine
        ports:
            - "80:80"
        volumes:
            - ./docker/web/conf/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
    php:
        build: ./docker/php
        volumes:
            - ./backend:/home/www/code
        working_dir: /home/www/code



